Add search benchmark
cloudant/fdblucene-perf pull request #1
Opened 2019-05-03 07:02 UTC by tonysun83

We separate the search benchmark into their own classes.

1) SearchSetup - Indexes 100k documents and creates a random array of search terms based on terms found in those 100k documents

2) FDBSearchSetup - Indexes 100k docs into FDB

3) NIOSSearchSetup - Indexes 100k docs into NIOSFileDirectory

4) BasicSearchBenchmark - Two search functions that is used for the benchmark. One takes in FDBSearchSetup as the state class parameter, and the other takes in NIOSSearchSetup

This acts as the foundation for the search benchmark.

2019-05-03 10:31 UTC, rnewson requested changes

2019-05-03 10:31 UTC, rnewson commented on src/main/java/com/cloudant/fdblucene/benchmark/BasicSearchBenchmark.java
> +    @Timeout(time = 5, timeUnit = TimeUnit.MINUTES)
why is timeout lower than the duration of an iteration?

2019-05-03 10:31 UTC, rnewson commented on src/main/java/com/cloudant/fdblucene/benchmark/BasicSearchBenchmark.java
> +    @GroupThreads(1)
why use Group or GroupThreads when we only have one thread for the tests and only one task in the benchmark?

2019-05-03 10:31 UTC, rnewson commented on src/main/java/com/cloudant/fdblucene/benchmark/BasicSearchBenchmark.java
> +        setup.searcher.search(new TermQuery(new Term("body", term)), setup.topNDocs);
we should return the result so that JMH can guard against dead code excision.

2019-05-07 05:42 UTC, tonysun83 commented
updated, but I want to switch over to using EnwikiSource.

2019-05-07 12:52 UTC, rnewson approved these changes

2019-05-07 12:52 UTC, rnewson commented
approved. let's merge this then cycle back to do the EnWiki documents and queries.

2019-05-08 04:19 UTC, merged